language: node_js
node_js:
  - "10"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t linbudu/docker-node-app:latest .
  - docker push linbudu/docker-node-app:latest
